spring:
  servlet:
    multipart:
      max-file-size:
        10MB
      max-request-size:
        50MB
  output:
    ansi:
      enabled: always
  config:
    import:
    - optional:file:.env[.properties]
  
  threads:
    virtual:
      enabled: true
  
  application:
    name: app
  

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
    hikari:
      pool-name: CosplayIncHikariPool
      maximum-pool-size: 15
      minimum-idle: 2
  
  data:
    redis:
      host: ${REDIS_HOSTS}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  mail:
    host: stmp.gmail.com
    port: 587
    username: ${JAVA_MAIL_USERNAME}
    password: ${JAVA_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  address: 0.0.0.0
  port: 80
GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
